# Generated by Django 5.2.1 on 2025-05-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_api_url', models.URLField(max_length=300, verbose_name='User API URL')),
                ('course_api_url', models.URLField(max_length=300, verbose_name='Course API URL')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Setting',
                'verbose_name_plural': 'API Settings',
            },
        ),
    ]
