# Generated by Django 5.2.1 on 2025-05-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apisettings',
            name='course_api_message',
            field=models.CharField(blank=True, help_text='Message shown when Course API is unreachable. Leave blank to use the default message.', max_length=255, verbose_name='Course API Error Message'),
        ),
        migrations.AddField(
            model_name='apisettings',
            name='user_api_message',
            field=models.CharField(blank=True, help_text='Message shown when User API is unreachable. Leave blank to use the default message.', max_length=255, verbose_name='User API Error Message'),
        ),
    ]
