# Generated by Django 5.2.1 on 2025-06-04 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_title_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='registration_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='middle_name',
            new_name='middleName',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='mobile_number',
            new_name='mobile',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Role/Title'),
        ),
    ]
