# Generated by Django 5.2.1 on 2025-06-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_age_remove_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='completeName',
        ),
        migrations.AddField(
            model_name='user',
            name='plain_password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Password (Unhashed)'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('learner', 'Learner'), ('instructor', 'Instructor'), ('admin', 'Admin')], max_length=20, null=True, verbose_name='Role/Title'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10, verbose_name='Status'),
        ),
    ]
